apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: hello-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: quay.io/jeeset/flask_3.1.3:v3.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
