apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-app-ns
resources:
- flask_web_app_namespace.yml
- flask_web_app_deployment.yml
- flask_web_app_service.yml
- flask_web_app_ingress.yml
images:
- name: flask
  newName: quay.io/jeeset/flask_3.1.3
  newTag: 537f68d0ca6a6a3a6e517691934c166382dd165e
