apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jeeset/gitops_cicd_pratice
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-app-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
